# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Leo Franco"
email: leodonethat@gmail.com
description: "Who is Leo?"
baseurl: ""
url: "https://www.leo.sh"
twitter_username: leodonethat
github_username: leodonethat

author:
  name: " "
  avatar: "/assets/images/leodonethat_sq.png"
  bio: "Passionate about data, <br>remote work, and an <br>internet without borders."
  email: "leodonethat@gmail.com"
  linkedin: "leo-franco-zh"
  instagram: "leobeenthere"
  github: "leodonethat"

social:
  type: Person
  name: leodonethat
  links:
    - "https://www.linkedin.com/in/leo-franco-zh/"
    - "https://github.com/leodonethat/"
    - "https://instagram.com/leobeenthere"

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
