# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Leo Franco
email: leodonethat@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Who is Leo and what has he done?
baseurl: ""
url: "https://www.leo.sh"
twitter_username: leodonethat
github_username: leodonethat

author:
  name: "Leo Franco"
  avatar: "/images/leodonethat_sq.png"
  bio: "Been **there**, done **that**."
  email: "leodonethat@gmail.com"
  linkedin: "leo-franco-zh"
  instagram: "leobeenthere"
  github: "leodonethat"

# Site Footer
footer:

# Build settings
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

social:
  type: Person
  name: leodonethat
  links:
    - "https://www.linkedin.com/in/leo-franco-zh/"
    - "https://github.com/leodonethat/"
    - "https://instagram.com/leobeenthere"
#    - "https://twitter.com/leodonethat"

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true

permalink: /:categories/:slug/
paginate: 5
paginate_path: /page:num/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
